# Generated by Django 3.1.3 on 2022-03-24 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0005_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='modify_Date',
            new_name='modify_date',
        ),
    ]
